"use client";
import Link from "next/link";
import { useState } from "react";

export default function SettingsPage() {
  const [saved, setSaved] = useState(false);
  return <main className="dashboard-page"><nav className="dashboard-nav shell"><Link className="brand" href="/">Refactor<span>Flow</span></Link><div className="dashboard-nav-links"><Link href="/dashboard">Dashboard</Link><Link href="/challenge">Challenges</Link><Link className="text-link" href="/signin">Sign out</Link></div></nav><section className="settings-content shell"><div className="settings-heading"><p className="kicker">Workspace settings</p><h1>Make it yours.</h1><p>Control your profile, preferences, and personal data.</p></div><div className="settings-layout"><aside className="settings-menu"><a href="#profile">Profile</a><a href="#preferences">Preferences</a><a href="#privacy">Privacy</a><a href="#account">Account</a></aside><div className="settings-sections"><section className="settings-section" id="profile"><p className="kicker">Profile</p><h2>Your details</h2><label>Display name<input defaultValue="Your name" /></label><label>Email address<input type="email" defaultValue="you@example.com" /></label></section><section className="settings-section" id="preferences"><p className="kicker">Preferences</p><h2>How RefactorFlow speaks to you</h2><label className="toggle-row"><span><strong>Weekly reflection reminder</strong><small>Receive a gentle reminder to review your process.</small></span><input type="checkbox" defaultChecked /></label><label className="toggle-row"><span><strong>Challenge recommendations</strong><small>Get suggestions based on your recent practice.</small></span><input type="checkbox" defaultChecked /></label></section><section className="settings-section" id="privacy"><p className="kicker">Privacy</p><h2>Your data, your control</h2><p className="settings-copy">Your individual behavioral data is private and belongs to you. Team reporting, when available, is aggregate-only.</p><Link className="secondary-button" href="/privacy">Read privacy policy <span>&rarr;</span></Link></section><section className="settings-section danger" id="account"><p className="kicker">Account</p><h2>Account actions</h2><p className="settings-copy">Export your reflections or permanently delete your account and associated data.</p><div className="settings-actions"><button className="secondary-button" onClick={() => setSaved(true)}>Save changes</button><button className="danger-button">Delete account</button></div>{saved && <p className="saved-message" role="status">Changes saved for this session.</p>}</section></div></div></section></main>;
}

