"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

const metrics = [["Sessions completed", "12", "+3 this week"], ["Thoughtful pauses", "68%", "+12% this month"], ["Current streak", "6 days", "Keep the loop going"]];
const prompts = ["Your dashboard is ready for a name with main-character energy.", "Quick quest: give your workspace a name so it knows who is steering.", "A blank name? Even brilliant builders deserve a tiny identity upgrade.", "Your future self says: add a display name and make it unmistakably yours."];

export default function DashboardPage() {
  const [showPrompt, setShowPrompt] = useState(false); const [displayName, setDisplayName] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { const name = window.localStorage.getItem("refactorflow-display-name") || ""; setDisplayName(name); if (!name) setShowPrompt(true); }, []);
  function saveName(event) { event.preventDefault(); const value = displayName.trim(); if (!value) return; window.localStorage.setItem("refactorflow-display-name", value); setShowPrompt(false); setMessage("Nice to meet you, " + value + "!"); }
  return <main className="dashboard-page"><nav className="dashboard-nav shell"><Link className="brand" href="/">Refactor<span>Flow</span></Link><div className="dashboard-nav-links"><Link href="/challenge">Challenges</Link><Link href="/report">Reports</Link><Link href="/settings">Settings</Link><Link className="text-link" href="/signin">Sign out</Link></div></nav>{showPrompt && <div className="dashboard-popup" role="dialog" aria-modal="true" aria-labelledby="name-popup-title"><button className="popup-close" aria-label="Close display name prompt" onClick={() => setShowPrompt(false)}>&times;</button><p className="kicker">A tiny welcome quest</p><h2 id="name-popup-title">What should we call you?</h2><p>{prompts[Math.floor(new Date().getDate() % prompts.length)]}</p><form onSubmit={saveName}><input autoFocus value={displayName} placeholder="Your display name" onChange={(event) => setDisplayName(event.target.value)} /><button className="primary-button">Save my name <span>&rarr;</span></button></form></div>}<section className="dashboard-hero shell"><div><p className="kicker">Your workspace</p><h1>Good to see you<br /><em>thinking clearly.</em></h1><p>Use today&apos;s challenge to keep building a more deliberate coding rhythm.</p>{message && <p className="saved-message" role="status">{message}</p>}</div><Link className="primary-button" href="/challenge">Start a challenge <span>&rarr;</span></Link></section><section className="metrics shell">{metrics.map(([label, value, note]) => <article className="metric" key={label}><span className="kicker">{label}</span><strong>{value}</strong><p>{note}</p></article>)}</section><section className="dashboard-grid shell"><article className="dashboard-panel challenge-panel"><div><p className="kicker">Next up</p><h2>Refactor under pressure</h2><p>Practice noticing the first moment you want to rewrite. Take a breath, name the hypothesis, then make the smallest useful change.</p></div><Link className="secondary-button" href="/challenge">View challenge <span>&rarr;</span></Link></article><article className="dashboard-panel"><p className="kicker">Your reflection</p><h2>Progress is a process.</h2><p>Your latest report is ready to review. See where your pauses helped and where you rushed.</p><Link className="secondary-button" href="/report">Open latest report <span>&rarr;</span></Link></article></section></main>;
}

